// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDRW9rxwc7s6C3CbxqqT67Ry1hzuu3BZc',
    appId: '1:126826542523:web:00b76c427c1de974d1c09e',
    messagingSenderId: '126826542523',
    projectId: 'fruits-hub-a498b',
    authDomain: 'fruits-hub-a498b.firebaseapp.com',
    storageBucket: 'fruits-hub-a498b.firebasestorage.app',
    measurementId: 'G-R13ZTXP6L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg4wo5M5qz5vLDb_0-uIWpotd_huAdIio',
    appId: '1:126826542523:android:cf02002bb2d70c4bd1c09e',
    messagingSenderId: '126826542523',
    projectId: 'fruits-hub-a498b',
    storageBucket: 'fruits-hub-a498b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEsjElf8XEeoXhVgw13qJAE9EK87lfKw',
    appId: '1:126826542523:ios:66503de6b5ef376ad1c09e',
    messagingSenderId: '126826542523',
    projectId: 'fruits-hub-a498b',
    storageBucket: 'fruits-hub-a498b.firebasestorage.app',
    androidClientId: '126826542523-j08np5hjssg4ubm13hfkivic2t5afpjq.apps.googleusercontent.com',
    iosClientId: '126826542523-kljirbvu10hrj3aegn4s23hc6lvkvvf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEsjElf8XEeoXhVgw13qJAE9EK87lfKw',
    appId: '1:126826542523:ios:66503de6b5ef376ad1c09e',
    messagingSenderId: '126826542523',
    projectId: 'fruits-hub-a498b',
    storageBucket: 'fruits-hub-a498b.firebasestorage.app',
    androidClientId: '126826542523-j08np5hjssg4ubm13hfkivic2t5afpjq.apps.googleusercontent.com',
    iosClientId: '126826542523-kljirbvu10hrj3aegn4s23hc6lvkvvf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDRW9rxwc7s6C3CbxqqT67Ry1hzuu3BZc',
    appId: '1:126826542523:web:85cbd97e2ed245cfd1c09e',
    messagingSenderId: '126826542523',
    projectId: 'fruits-hub-a498b',
    authDomain: 'fruits-hub-a498b.firebaseapp.com',
    storageBucket: 'fruits-hub-a498b.firebasestorage.app',
    measurementId: 'G-74ST1L51XY',
  );
}
